chat/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.views.static import serve
from django.urls import include
from robot.views import *
from .settings import STATIC_ROOT
from .settings import MEDIA_ROOT,MEDIA_URL

from django.conf.urls.static import static
from . import settings
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    url('captcha', include("captcha.urls")),
    path('refresh_captcha/', refresh_captcha),    # 刷新验证码，ajax
    path('', Index.as_view(), name="index"),
    path('record', record, name="search"),
    path('login', Login.as_view(), name="login"),
    path('logout', logoutView, name="logout"),
    path('register', RegisterView.as_view(), name='register'),
    path('upload',upload, name='upload'),
    path('mode1',mode1,name='mode1'),
    path('mode2',mode2,name='mode2'),
    path('chart',chart,name='chart'),
    path('info_finish',info_finish,name='info_finish'),
    path('test',test,name='test'),
    path(r'media/(?P<path>.*)', serve,{'document_root': MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]+static(MEDIA_URL, document_root=MEDIA_ROOT)

# from django.conf import settings

# if settings.DEBUG:
#     from django.conf.urls.static import static

#     urlpatterns += static(
#         settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
#     )

robot/forms.py
from django import forms
from captcha.fields import CaptchaField
from robot.models import Users

class LoginForm(forms.Form):
    username = forms.CharField(label='用户名', min_length=1, error_messages={'required': '请填写用户名', 'max_length':'用户名过长', 'min_length': '用户名过短'})
    password = forms.CharField(label='密码', min_length=6, max_length=20, error_messages={'required': '请填写用密码','max_length':'密码过长', 'min_length': '密码过短'})


class RegisterForm(forms.Form):
    email = forms.EmailField(label='邮箱', min_length=3, error_messages={'required': '请填写电子邮件', 'min_length': '邮箱过短'})
    username = forms.CharField(label='用户名', min_length=1, error_messages={'required': '请填写用户名', 'max_length':'用户名过长', 'min_length': '用户名过短'})
    password = forms.CharField(label='密码', min_length=6, max_length=20, error_messages={'required': '请填写密码','max_length':'密码过长', 'min_length': '密码过短'})
    captcha = forms.CharField(label='验证码',  error_messages={'required': '请填写验证码'})


class registerForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = ['email', 'username', 'password']

class ModeForm(forms.Form):
    username = forms.CharField(label='用户名', min_length=1, error_messages={'required': '请填写用户名', 'max_length':'用户名过长', 'min_length': '用户名过短'})
    mode = forms.CharField(label='模式',max_length=2)

templates/index.html
<html>
{% load static %}

<head>
    <title>chat UI</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="author" content="https://blog.csdn.net/q475254344">
    <link rel="icon" type="image/x-icon" href="{% static 'images/icon36.png' %}">
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
        crossorigin="anonymous">
</head>
<script>
    document.getElementsByTagName('body').height = window.innerHeight;
</script>
<link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css">
<body class="box">
    <div class="leftbar">
        <ul>
            <a href="{% url 'chart' %}"> <li><i class="fas fa-user"></i></li></a>
            <a href="{% url 'logout' %}"><li><i class="fas fa-power-off"></i></li></a>
            <!-- <li><i class="fas fa-users"></i></li>
            <li><i class="fas fa-smile"></i></li>
            <li><i class="fas fa-envelope"></i></li>
            <li><i class="fas fa-bell"></i></li>
            <li><i class="fas fa-calendar-alt"></i></li>
            <li><i class="fas fa-power-off"></i></li> -->
        </ul>
    </div>
    <div class="container">
        <div class="chatbox">
            <div class="chatleft" >
                <div class="top">
                    <i class="fas fa-bars" style="font-size: 1.4em"></i>
                    <!-- <input type="text" placeholder="search" style="width: 140px; height: 36px; margin-left: 25px;"> -->
                    &nbsp;&nbsp;<a href="{% url 'search' %}"><button class="sendbtn">record</button></a>
                    <!-- <a href="/"><button class="searchbtn"><i class="fas fa-search"></i></button></a> -->
                    <a href="/"><button class="searchbtn">chat</button></a>&nbsp;&nbsp;
                </div>
                <div class="center">
                    <ul>
                        <a href="{% url 'mode1' %}">
                            <li>
                                <img style="border-radius: 20px; vertical-align: middle;" src="{% static 'images/icon36.png' %}" width="40px">
                                <span style="margin-left: 10px;">灵魂小伴侣</span>
                            </li>
                        </a>
                        <a href="{% url 'mode2' %}">
                            <li>
                                <img style="border-radius: 20px; vertical-align: middle;" src="{% static 'images/icon36.png' %}" width="40px">
                                <span style="margin-left: 10px;">饮食小伴侣</span>
                            </li>
                        </a>

                    </ul>
                </div>
            </div>
            <div class="chatright">
                <div class="top">
                    <img style="border-radius: 20px; vertical-align: middle;" src="{% static 'images/icon36.png' %}" width="40px">
                    {% if mode == '1'%}
                    <span style="margin-left: 20px;">灵魂小伴侣</span>
                    {% endif %}
                    {% if mode == '2'%}
                    <span style="margin-left: 20px;">饮食小伴侣</span>
                    {% endif %}
                    <!-- <i  style="font-size: 1em; position: absolute; right: 20px; color: gray;"><a href="{% url 'logout' %}"><button class="sendbtn">logout</button></a></i> -->
                </div>
                {% block content %}
                {% if recevie %}
                <div class="center">
                    <ul>
                        {% if comment %}
                        <li class="msgright">
                            <p class="msgcard">{{ comment }}</p>
                        </li>
                        {% endif %}
                        {% if pic_path %}
                        <li class="msgright">
                            <img class="msgpic" src={{ pic_path.url}} height="100" width="100" align="right"/>
                        </li>
                        {% endif %}
                        <li class="msgleft">
                            <img style="border-radius: 20px; vertical-align: top;" src="{% static 'images/icon36.png' %}" width="40px">
                            <p class="msgcard">{{ recevie }}</p>
                        </li>

                    </ul>
                </div>
                
                {% else %}
                <div class="center">

                </div>
                {% endif %}
                <div class="footer">
                    <form action="{% url 'upload' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <input type="file" name="fafafa">
                        <input type="submit">
                    </form>
                    <!-- <input type="file" name="file" value="上传图片" id="file_upload">
                    <input type="button" value="上传" onclick="FileUpload()"> -->
                    <form method="post" action="{% url 'index' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <textarea name="comment" maxlength="800" rows="5" cols="40" style="width: 100%; resize: none; border: none; "
                            placeholder="请在此输入要发送的内容..."></textarea>
                        <button class="sendbtn" style="margin-top: -20px;">发送</button>
                    </form>
                </div>
                {% endblock %}
            </div>
        </div>
    </div>
</body>
<!-- <script src="/static/js/jquery-3.2.1.min.js"></script>
<script>
    function FileUpload() {
            var form_data = new FormData();
            var file_info =$('#file_upload')[0].files[0];
            alert(file_info)
            form_data.append('file',file_info);
            //if(file_info==undefined)暂且不许要判断是否有附件
                //alert('你没有选择任何文件');
                //return false
            $.ajax({
                url:'/upload_ajax/',
                type:'POST',
                data: form_data,
                processData: false,  // tell jquery not to process the data
                contentType: false, // tell jquery not to set contentType
                success: function(callback) {

                    console.log('ok')
                }
            });

            }</script> -->
</html>

templates/info.html
{% extends 'login.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/jquery-2.0.0.min.js' %}"></script>
<div class="demo" style="padding: 20px 0; margin-top: 100px;">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-3 col-md-6">
                <form class="form-horizontal" method="POST" action="{% url 'info_finish' %}">
                    {% csrf_token %}
                    <span class="heading">健康信息填写</span>
                    <div class="form-group">
                        <input type="text" class="form-control" name="username" id="inputEmail3" value="{{username}}" readonly="readonly">
                        <!-- <i class="fa fa-user"></i> -->
                        <i><img src="{% static 'images/ios7-person.png' %}" width="17px"></i>
                    </div>
                    <div class="form-group row">
                        <select name="gender" class="form-control mb-3">
                            <option >请选择性别</option>
                            <option value="male">男</option>
                            <option value="female">女</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="age" id="inputEmail3" placeholder="年龄">
                        <!-- <i class="fa fa-user"></i> -->
                        <i><img src="{% static 'images/ios7-person.png' %}" width="17px"></i>
                    </div>
                    <div class="form-group help">
                        <input type="text" class="form-control" name="height" id="inputEmail3" placeholder="身高">
                        <!-- <i class="fa fa-lock"></i>
                            <a href="#" class="fa fa-question-circle"></a> -->
                        <i><img src="{% static 'images/ios7-unlocked.png' %}" width="17px"></i>
                    </div>
                    <div class="form-group help">
                        <input type="text" class="form-control" name="weight" id="inputEmail3" placeholder="体重">
                        <!-- <i class="fa fa-lock"></i>
                            <a href="#" class="fa fa-question-circle"></a> -->
                        <i><img src="{% static 'images/ios7-unlocked.png' %}" width="17px"></i>
                    </div>
                    <div class="form-group row">
                        <select name="target" class="form-control mb-3">
                            <option >请选择目标</option>
                            <option value="lose">减重</option>
                            <option value="keep">保持</option>
                            <option value="gain">增重</option>
                        </select>
                    </div>
                    <div class="form-group row">
                        <select name="freqency" class="form-control mb-3">
                            <option >请选择运动频率</option>
                            <option value="barely">几乎不运动</option>
                            <option value="seldom">很少运动</option>
                            <option value="medium">适量运动</option>
                            <option value="active">经常运动</option>
                            <option value="professional">健身达人</option>
                        </select>
                    </div>
                    
                    <div class="form-group">
                        {% for key,error in register_form.errors.items %}{{ error }}{% endfor %} {{ msg }}
                    </div>
                    <div class="form-group">
                        <div >
                            <!-- <input type="checkbox" value="None" id="checkbox1" name="check"> -->
                            <!-- <label for="checkbox1"></label> -->
                            
                        </div>
                        <!-- <a href="/" style="color:grey"><span class="text"><img src="{% static 'images/home.png' %}" width="20px">&nbsp;返回登录</span></a> -->
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- ajax刷新验证码 -->
<script>
    // 也能刷新验证码
    // $(document).ready(function () {
    //     $('.captcha').click(function () {
    //         $.getJSON("refresh_captcha", function (result) {
    //             // console.log(result)
    //             $('#id_captcha').attr('src', result['image_url']);
    //             $('#id_captcha_0').val(result['hashkey'])
    //         });
    //     });
    // });

     $(".captcha").click(function () {
        $.ajax({
            url: "refresh_captcha",
            dataType: 'json',
            success: function (result) {
                // console.log(result)
                $('#id_captcha').attr('src', result['image_url']);
                $('#id_captcha_0').val(result['hashkey'])
            }
        });
    });
</script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
{% load static%}
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
<link rel="icon" type="image/x-icon" href="{% static 'images/icon36.png' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>chat UI</title>

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}">

</head>
<body>
{% block content %}
<div class="demo" style="padding: 20px 0; margin-top: 100px;">
	<div class="container">
		<div class="row">
			<div class="col-md-offset-3 col-md-6">
				<form class="form-horizontal" method="POST" action="{% url 'login' %}">
                    {% csrf_token %}
					<span class="heading">用户登录</span>
					<div class="form-group">
						<input type="text" class="form-control" name="username" id="inputEmail3" placeholder="用户名或电子邮件">
                        <!-- <i class="fa fa-user"></i> -->
                        <i><img src="{% static 'images/ios7-person.png' %}" width="17px"></i>
					</div>
					<div class="form-group help">
						<input type="password" class="form-control" name="password" id="inputPassword3" placeholder="密　码">
						<!-- <i class="fa fa-lock"></i>
                        <a href="#" class="fa fa-question-circle"></a> -->
                        <i><img src="{% static 'images/ios7-unlocked.png' %}" width="17px"></i>
                    </div>
                    <div class="form-group">
                        {% for key,error in login_form.errors.items %}{{ error }}{% endfor %} {{ msg }}
                    </div>
					<div class="form-group">
						<div >
							<!-- <input type="checkbox" value="None" id="checkbox1" name="check">
							<label for="checkbox1"></label> -->
						</div>
						<a href="{% url 'register' %}" style="color:grey"><span class="text"><img src="{% static 'images/ios7-personadd.png' %}" width="20px">&nbsp;点击注册</span></a>
						<button type="submit" class="btn btn-default">登录</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}
</body>
</html>

templates/record.html
{% extends 'index.html' %}
{% load static%}
{% block content %} 
<div class="center" style="height: 90%">
    {% for chat in all_chats %}
    <ul>
   
    <li class="msgleft">
        <p class="msgcard">{{ chat.chat_comment }} </p>
        <p style="font-size: 10px;">{{ chat.send_time | date:"Y/m/d  H:i:s" }}</p>
    </li>
   
    </ul>
    {% endfor %}
</div> 
{% endblock %}

templates/register.html
{% extends 'login.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/jquery-2.0.0.min.js' %}"></script>
<div class="demo" style="padding: 20px 0; margin-top: 100px;">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-3 col-md-6">
                <form class="form-horizontal" method="POST" action="{% url 'register' %}">
                    {% csrf_token %}
                    <span class="heading">用户注册</span>
                    <div class="form-group">
                        <input type="text" class="form-control" name="email" id="inputEmail3" placeholder="电子邮件">
                        <!-- <i class="fa fa-user"></i> -->
                        <i><img src="{% static 'images/email.png' %}" width="17px"></i>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="username" id="inputEmail3" placeholder="用户名">
                        <!-- <i class="fa fa-user"></i> -->
                        <i><img src="{% static 'images/ios7-person.png' %}" width="17px"></i>
                    </div>
                    <div class="form-group help">
                        <input type="password" class="form-control" name="password" id="inputPassword3" placeholder="密　码">
                        <!-- <i class="fa fa-lock"></i>
                            <a href="#" class="fa fa-question-circle"></a> -->
                        <i><img src="{% static 'images/ios7-unlocked.png' %}" width="17px"></i>
                    </div>

                    <div class="form-group help">
                        <i><img src="{% static 'images/load-a.png' %}" width="17px"></i>
                        <input type="text" name='captcha' class="form-control" placeholder="验证码" style="width: 81%; display: inline-block;">
                        <a href="#" class="captcha" style="color:grey"><img src="{{ captcha.image_url }}" alt="点击换一张" id="id_captcha"></a>
                        <input value="{{ captcha.hashkey }}" name="hashkey" type="hidden" id="id_captcha_0">

                    </div>
                    <div class="form-group">
                        {% for key,error in register_form.errors.items %}{{ error }}{% endfor %} {{ msg }}
                    </div>
                    <div class="form-group">
                        <div >
                            <!-- <input type="checkbox" value="None" id="checkbox1" name="check"> -->
                            <!-- <label for="checkbox1"></label> -->
                            
                        </div>
                        <a href="/" style="color:grey"><span class="text"><img src="{% static 'images/home.png' %}" width="20px">&nbsp;返回登录</span></a>
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- ajax刷新验证码 -->
<script>
    // 也能刷新验证码
    // $(document).ready(function () {
    //     $('.captcha').click(function () {
    //         $.getJSON("refresh_captcha", function (result) {
    //             // console.log(result)
    //             $('#id_captcha').attr('src', result['image_url']);
    //             $('#id_captcha_0').val(result['hashkey'])
    //         });
    //     });
    // });

     $(".captcha").click(function () {
        $.ajax({
            url: "refresh_captcha",
            dataType: 'json',
            success: function (result) {
                // console.log(result)
                $('#id_captcha').attr('src', result['image_url']);
                $('#id_captcha_0').val(result['hashkey'])
            }
        });
    });
</script>
{% endblock %}